=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunSampleSheetChange/SequenceRunSampleSheetChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/sequencerunmanager/SequenceRunSampleSheetChange.schema.json",
  "description": "EventBridge custom event schema for orcabus.sequencerunmanager@SequenceRunSampleSheetChange",
  "title": "AWSEvent",
  "definitions": {
    "SequenceRunSampleSheetChange": {
      "type": "object",
      "required": ["instrumentRunId", "timeStamp", "sampleSheetName", "samplesheetbase64gz"],
      "properties": {
        "instrumentRunId": {
          "type": "string"
        },
        "sequenceRunId": {
          "type": "string"
        },
        "timeStamp": {
          "type": "string"
        },
        "sampleSheetName": {
          "type": "string"
        },
        "samplesheetbase64gz": {
          "type": "string"
        },
        "comment": {
          "$ref": "#/definitions/Comment"
        }
      }
    },
    "Comment": {
      "type": "object",
      "required": ["comment", "created_by", "created_at"],
      "properties": {
        "comment": {
          "type": "string"
        },
        "created_by": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/SequenceRunSampleSheetChange"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunSampleSheetChange/examples/SRSSC.json
{
  "version": "0",
  "id": "12345678-90ab-cdef-1234-567890abcdef",
  "detail-type": "SequenceRunSampleSheetChange",
  "source": "orcabus.sequencerunmanager",
  "account": "000000000000",
  "time": "2024-04-27T03:45:02.113245Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "instrumentRunId": "123456_A7890_1234_ABCDEFGH",
    "sequenceRunId": "r.1234567890abcdefghijklmn",
    "timeStamp": "2024-04-27T03:45:02.113245Z",
    "sampleSheetName": "sampleSheet_v2.csv",
    "samplesheetbase64gz": "base64_encoded_samplesheet........",
    "comment": {
      "comment": "comment",
      "created_by": "user",
      "created_at": "2024-04-27T03:45:02.113245Z"
    }
  }
}
